basePath: /api/v1
definitions:
  github_com_Rics69_x-net_internal_core_transport_http_response.ErrorResponse:
    properties:
      error:
        example: full error text
        type: string
      message:
        example: short message
        type: string
    type: object
  internal_features_auth_transport_http.LoginRequest:
    properties:
      password:
        example: supersecret
        type: string
      username:
        example: ivan_ivanov
        type: string
    required:
    - password
    - username
    type: object
  internal_features_auth_transport_http.LoginResponse:
    properties:
      created_at:
        example: "2026-10-04T12:00:00Z"
        type: string
      full_name:
        example: Ivan Ivanov
        type: string
      id:
        example: 1
        type: integer
      username:
        example: ivan_ivanov
        type: string
    type: object
  internal_features_auth_transport_http.RegisterRequest:
    properties:
      full_name:
        example: Ivan Ivanov
        maxLength: 100
        minLength: 3
        type: string
      password:
        example: supersecret
        maxLength: 72
        minLength: 8
        type: string
      phone_number:
        example: "+79999998877"
        maxLength: 15
        minLength: 10
        type: string
      username:
        example: ivan_ivanov
        maxLength: 32
        minLength: 3
        type: string
    required:
    - full_name
    - password
    - username
    type: object
  internal_features_auth_transport_http.RegisterResponse:
    properties:
      created_at:
        example: "2026-10-04T12:00:00Z"
        type: string
      full_name:
        example: Ivan Ivanov
        type: string
      id:
        example: 1
        type: integer
      username:
        example: ivan_ivanov
        type: string
    type: object
  internal_features_users_transport_http.GetMeResponse:
    properties:
      created_at:
        example: "2026-10-04T12:00:00Z"
        type: string
      full_name:
        example: Ivan Ivanov
        type: string
      id:
        example: 1
        type: integer
      phone_number:
        example: "+79999998877"
        type: string
      username:
        example: ivan_ivanov
        type: string
      version:
        example: 3
        type: integer
    type: object
  internal_features_users_transport_http.GetUserResponse:
    properties:
      created_at:
        example: "2026-10-04T12:00:00Z"
        type: string
      full_name:
        example: Ivan Ivanov
        type: string
      id:
        example: 1
        type: integer
      phone_number:
        example: "+79999998877"
        type: string
      username:
        example: ivan_ivanov
        type: string
      version:
        example: 3
        type: integer
    type: object
  internal_features_users_transport_http.PatchUserRequest:
    properties:
      full_name:
        example: Иван Иванов
        type: string
      phone_number:
        example: "+79998887766"
        type: string
    type: object
  internal_features_users_transport_http.PatchUserResponse:
    properties:
      created_at:
        example: "2026-10-04T12:00:00Z"
        type: string
      full_name:
        example: Ivan Ivanov
        type: string
      id:
        example: 1
        type: integer
      phone_number:
        example: "+79999998877"
        type: string
      username:
        example: ivan_ivanov
        type: string
      version:
        example: 3
        type: integer
    type: object
  internal_features_users_transport_http.UserDTOResponse:
    properties:
      created_at:
        example: "2026-10-04T12:00:00Z"
        type: string
      full_name:
        example: Ivan Ivanov
        type: string
      id:
        example: 1
        type: integer
      phone_number:
        example: "+79999998877"
        type: string
      username:
        example: ivan_ivanov
        type: string
      version:
        example: 3
        type: integer
    type: object
host: 127.0.0.1:5050
info:
  contact: {}
  description: X-Chat App REST-API schema
  title: X-Chat API
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: |-
        Проверка username/пароля. При успехе выставляется httpOnly cookie `access_token`,
        после чего защищённые ручки (в т.ч. из этого Swagger UI) работают автоматически
      parameters:
      - description: Login тело запроса
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/internal_features_auth_transport_http.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Успешный вход
          schema:
            $ref: '#/definitions/internal_features_auth_transport_http.LoginResponse'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/github_com_Rics69_x-net_internal_core_transport_http_response.ErrorResponse'
        "401":
          description: Invalid username or password
          schema:
            $ref: '#/definitions/github_com_Rics69_x-net_internal_core_transport_http_response.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/github_com_Rics69_x-net_internal_core_transport_http_response.ErrorResponse'
      summary: Вход
      tags:
      - auth
  /auth/logout:
    post:
      description: 'Сбрасывает cookie `access_token`. Авторизация не требуется: выйти
        можно и с протухшим токеном'
      responses:
        "204":
          description: Успешный выход
      summary: Выход
      tags:
      - auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: Создание нового пользователя. При успехе сразу выставляется httpOnly
        cookie `access_token`
      parameters:
      - description: Register тело запроса
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/internal_features_auth_transport_http.RegisterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Успешно зарегистрированный пользователь
          schema:
            $ref: '#/definitions/internal_features_auth_transport_http.RegisterResponse'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/github_com_Rics69_x-net_internal_core_transport_http_response.ErrorResponse'
        "409":
          description: Username already taken
          schema:
            $ref: '#/definitions/github_com_Rics69_x-net_internal_core_transport_http_response.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/github_com_Rics69_x-net_internal_core_transport_http_response.ErrorResponse'
      summary: Регистрация
      tags:
      - auth
  /users:
    get:
      description: Просмотр списка пользователей с опциональной пагинацией
      parameters:
      - description: Размер страницы с пользователями
        in: query
        name: limit
        type: integer
      - description: Смещение страницы с пользователями
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Успешное получение списка пользователей
          schema:
            items:
              $ref: '#/definitions/internal_features_users_transport_http.UserDTOResponse'
            type: array
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/github_com_Rics69_x-net_internal_core_transport_http_response.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/github_com_Rics69_x-net_internal_core_transport_http_response.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/github_com_Rics69_x-net_internal_core_transport_http_response.ErrorResponse'
      summary: Список пользователей
      tags:
      - users
  /users/{id}:
    get:
      description: Получение конкретного пользователя по его ID
      parameters:
      - description: ID получаемого пользователя
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Пользователь успешно найден
          schema:
            $ref: '#/definitions/internal_features_users_transport_http.GetUserResponse'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/github_com_Rics69_x-net_internal_core_transport_http_response.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/github_com_Rics69_x-net_internal_core_transport_http_response.ErrorResponse'
        "404":
          description: User not found
          schema:
            $ref: '#/definitions/github_com_Rics69_x-net_internal_core_transport_http_response.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/github_com_Rics69_x-net_internal_core_transport_http_response.ErrorResponse'
      summary: Получение пользователя
      tags:
      - users
  /users/me:
    delete:
      description: Удаление авторизованного пользователя. Кука при этом не чистится
        - после удаления фронт должен вызвать /auth/logout
      responses:
        "204":
          description: Успешное удаление пользователя
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/github_com_Rics69_x-net_internal_core_transport_http_response.ErrorResponse'
        "404":
          description: User not found
          schema:
            $ref: '#/definitions/github_com_Rics69_x-net_internal_core_transport_http_response.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/github_com_Rics69_x-net_internal_core_transport_http_response.ErrorResponse'
      summary: Удаление своего аккаунта
      tags:
      - users
    get:
      description: Получение профиля авторизованного пользователя (по access_token
        из cookie)
      produces:
      - application/json
      responses:
        "200":
          description: Текущий пользователь
          schema:
            $ref: '#/definitions/internal_features_users_transport_http.GetMeResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/github_com_Rics69_x-net_internal_core_transport_http_response.ErrorResponse'
        "404":
          description: User not found
          schema:
            $ref: '#/definitions/github_com_Rics69_x-net_internal_core_transport_http_response.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/github_com_Rics69_x-net_internal_core_transport_http_response.ErrorResponse'
      summary: Текущий пользователь
      tags:
      - users
    patch:
      consumes:
      - application/json
      description: |-
        Изменение профиля авторизованного пользователя
        ### Логика обновления полей (Three-state logic):
        1. **Поле не передано**: `phone_number`игнорируется, значение в БД не меняется
        2. **Явно передано значение**: `"phone_number": "+79998887766"` - устанавливает новый номер телефона
        3 . **Передан null**: `"phone_number": null` - очищает поле в БД (set to NULL)
        Ограничения: `full_name` не может быть выставлен как NULL
      parameters:
      - description: PatchUser тело запроса
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/internal_features_users_transport_http.PatchUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Успешно измененный пользователь
          schema:
            $ref: '#/definitions/internal_features_users_transport_http.PatchUserResponse'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/github_com_Rics69_x-net_internal_core_transport_http_response.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/github_com_Rics69_x-net_internal_core_transport_http_response.ErrorResponse'
        "404":
          description: User not found
          schema:
            $ref: '#/definitions/github_com_Rics69_x-net_internal_core_transport_http_response.ErrorResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/github_com_Rics69_x-net_internal_core_transport_http_response.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/github_com_Rics69_x-net_internal_core_transport_http_response.ErrorResponse'
      summary: Изменение своего профиля
      tags:
      - users
swagger: "2.0"
